development:
  secret_key_base: 1a37301cd396b6f2d5feed848674ba821af5390057b61db98ad6507fc63214bf146f29dbbc48dbb02abe84a94eea33d68e4b72c71a4fdb7643ff2f28379dbd81
  aws_bucket_region: <%= ENV['RECRUITING_BOARD_S3_REGION'] %>
  aws_access_key_id: <%= ENV['RECRUITING_BOARD_S3_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['RECRUITING_BOARD_S3_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['RECRUITING_BOARD_S3_BUCKET'] %>
  searchkick_reduced_usage: <%= ENV['RECRUITING_BOARD_SEARCHKICK_REDUCED_USAGE'] %>
  mandrill_username: <%= ENV['RECRUITING_BOARD_MANDRILL_USERNAME'] %>
  mandrill_password: <%= ENV['RECRUITING_BOARD_MANDRILL_PASSWORD'] %>
  fb_app_id: 446649385502732
  fb_app_secret: f0a795fbeea48830287857fb344541f3

test:
  secret_key_base: 954eb14c37fb45ae558c2c67455a2de4727f17e73b1bbf5f7e65a56e2fb9ec8dab7171a083a7c1b1c71a4ac6e9546118b8a545af76c00754d3356af670051dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_region: <%= ENV['RECRUITING_BOARD_S3_REGION'] %>
  aws_access_key_id: <%= ENV['RECRUITING_BOARD_S3_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['RECRUITING_BOARD_S3_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['RECRUITING_BOARD_S3_BUCKET'] %>
  reduced_searchkick_usage: <%= ENV['RECRUITING_BOARD_SEARCHKICK_REDUCED_USAGE'] %>
  mandrill_username: <%= ENV['RECRUITING_BOARD_MANDRILL_USERNAME'] %>
  mandrill_password: <%= ENV['RECRUITING_BOARD_MANDRILL_PASSWORD'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_region: <%= ENV['RECRUITING_BOARD_S3_REGION'] %>
  aws_access_key_id: <%= ENV['RECRUITING_BOARD_S3_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['RECRUITING_BOARD_S3_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['RECRUITING_BOARD_S3_BUCKET'] %>
  reduced_searchkick_usage: <%= ENV['RECRUITING_BOARD_SEARCHKICK_REDUCED_USAGE'] %>
  mandrill_username: <%= ENV['RECRUITING_BOARD_MANDRILL_USERNAME'] %>
  mandrill_password: <%= ENV['RECRUITING_BOARD_MANDRILL_PASSWORD'] %>
  include_analytics: <%= ENV['INCLUDE_ANALYTICS'] %>
  fb_app_id: <%= ENV['FB_APP_ID'] %>
  fb_app_secret: <%= ENV['FB_APP_SECRET'] %>

